apiVersion: apps/v1
kind: Deployment
metadata:
  name: wraith
  labels:
    app: wraith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wraith
  template:
    metadata:
      name: wraith
      labels:
        app: wraith
    spec:
      containers:
        - name: wraith
          image: ghcr.io/zgamelogic/wraith:master
          imagePullPolicy: Always
          volumeMounts:
            - name: keystore-volume
              mountPath: "/etc/keystore"
              readOnly: true
      volumes:
        - name: keystore-volume
          secret:
            secretName: ssl-keystore-secret
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret

      