apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wraith-ingress
spec:
  rules:
    - host: "wraith.zgamelogic.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wraith-bot
                port:
                  number: 2002
  tls:
    - hosts:
        - "wraith.zgamelogic.com"
      secretName: ingress-tls
