apiVersion: v1
kind: Service
metadata:
  name: wraith
spec:
  selector:
    app: wraith
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
      nodePort: 30010
  type: NodePort
  externalTrafficPolicy: Local
  