name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
    build:
        uses: ZGameLogic/kubernetes-action/.github/workflows/deploy.yml@master
        secrets: inherit
        with:
            KUBERNETES_DEPLOY: wraith
        permissions: write-all
