name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
    build:
        uses: ZGameLogic/kubernetes-action@v0.0.1
        secrets: inherit
        with:
            KUBERNETES_DEPLOY: wraith
