name: Deploy Wraith

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: zgamelogic/github-actions/.github/workflows/kubernetes-deploy.yaml@0.0.1
    with:
      applicationId: 3
      monitorIds: '3'
      environment: production
      deploymentName: wraith
      imageName: wraith