name: Docker Image CI

on:
  push:
    branches: [ "development" ]
jobs:
    Kubernetes:
        runs-on: PiServer
        steps:
            - name: Checkout Kubernetes Directory
              uses: actions/checkout@v4
              with:
                sparse-checkout: 'kubernetes/'
            - name: Apply Kubernetes Configuration
              id: apply
              run: |
                output=$(sudo kubectl apply -f kubernetes/)
                echo "##[set-output name=result;]$(echo $output)"

            - name: Check Deployment Status
              id: check
              run: |
                echo "Result was '${{ steps.apply.outputs.result }}'"
                unchanged=$(echo '${{ steps.apply.outputs.result }}' | grep 'deployment.apps/' | grep 'unchanged')
                if [ -z "$unchanged" ]; then
                  echo "Some deployments changed or other updates"
                  echo "::set-output name=unchanged::false"
                else
                  echo "All targeted deployments unchanged"
                  echo "::set-output name=unchanged::true"
                fi

            - name: Rolling update for unchanged deployments
              if: steps.check.outputs.unchanged == 'true'
              run: |
                deployments=$(echo "${{ steps.apply.outputs.result }}" | grep 'deployment.apps/' | grep 'unchanged' | awk '{print $1}')
                for deployment in $deployments; do
                  echo "Restarting deployment: $deployment"
                  sudo kubectl rollout restart $deployment
                done