name: Docker Image CI

on:
  push:
    branches: [ "development" ]
jobs:
    Kubernetes:
        runs-on: PiServer
        steps:
            - name: Checkout Kubernetes Directory
              uses: actions/checkout@v4
              with:
#                path: 'kubernetes'
                sparse-checkout: 'kubernetes/'
            - name: Apply Kubernetes Configuration
              run: sudo kubectl apply -f kubernetes/
#            - name: Rolling update
#              run: sudo kubectl rollout restart deployment wraith
